# -*- coding: utf-8 -*-
"""RF_v5_finetune.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Bad5x_YXoQVttMjoJwnL9qoIdnHbE_K
"""

# ======================================
# MOUNT GOOGLE DRIVE & SETUP PATHS
# ======================================
from google.colab import drive
import os

# Mount Google Drive (will prompt for authorization)
drive.mount('/content/drive')

# Define your Capstone data directory
DRIVE_DIR = '/content/drive/My Drive/CapstoneRFData'

if not os.path.exists(DRIVE_DIR):
    print(f"Warning: Directory not found at {DRIVE_DIR}. Please check the path.")
else:
    print(f"Successfully connected to {DRIVE_DIR}")

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_recall_fscore_support
import numpy as np
import joblib
import os
from datetime import datetime
import json

# ======================================
# LOAD THE MIDDLE-SPLIT DATASET
# ======================================
DATA_PATH = os.path.join(DRIVE_DIR, 'wetland_dataset_middle_split.npz')

print("Loading dataset...")
data = np.load(DATA_PATH)
X_train = data['X_train']
y_train_raw = data['y_train']
X_test  = data['X_test']
y_test_raw  = data['y_test']
test_row_min = int(data['test_row_min'])
test_row_max = int(data['test_row_max'])
data.close()

print(f"Loaded dataset from: {DATA_PATH}")
print(f"Total samples — Train: {X_train.shape[0]:,} | Test: {X_test.shape[0]:,}")

# ======================================
# TRANSFORM LABELS FOR BINARY CLASSIFICATION
# ======================================
# Class 0 remains 0 (Background). Classes 1-5 become 1 (Wetland).
y_train = (y_train_raw != 0).astype(int)
y_test  = (y_test_raw != 0).astype(int)

print(f"\nAfter converting to binary labels (0 = Background, 1 = Wetland):")
print(f"  Train classes present: {sorted(np.unique(y_train).tolist())}")
print(f"  Test  classes present: {sorted(np.unique(y_test).tolist())}")

# ======================================
# RECALCULATE CLASS WEIGHTS (Binary)
# ======================================
unique_classes, class_counts = np.unique(y_train, return_counts=True)
n_total = len(y_train)
n_classes = len(unique_classes)

# Balanced weighting
class_weight_dict = {
    int(cls): float(n_total / (n_classes * count))
    for cls, count in zip(unique_classes, class_counts)
}

# --- NEW: MANUAL WEIGHT ADJUSTMENT ---
# Boost the Background (Class 0) weight to aggressively reduce false positives.
# A factor of 1.5 is a good starting point. Increase if you still see too much leakage.
BACKGROUND_BOOST = 2
class_weight_dict[0] = class_weight_dict[0] * BACKGROUND_BOOST
# -------------------------------------

print(f"\nCalculated class weights (Binary - with x{BACKGROUND_BOOST} Background Boost):")
for cls, w in class_weight_dict.items():
    count = class_counts[list(unique_classes).index(cls)]
    label_name = "Background" if cls == 0 else "Wetland"
    print(f"  Class {cls} ({label_name}): weight={w:.4f}  (n={count:,})")

# ======================================
# TRAIN THE MODEL
# ======================================
rf_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=25,
    min_samples_leaf=20,
    random_state=42,
    class_weight=class_weight_dict,
    verbose=2,
    n_jobs=-1, # Uses all available Colab CPU cores
)

print(f"\n{'='*60}")
print("TRAINING (Stage 1 Binary: Background vs. Wetland)")
print(f"{'='*60}")
rf_model.fit(X_train, y_train)

# ======================================
# EVALUATE ON HELD-OUT GEOGRAPHIC REGION
# ======================================
y_pred = rf_model.predict(X_test)

labels = [0, 1]
target_names = ['Background (0)', 'Wetland (1)']

precision, recall, f1, support = precision_recall_fscore_support(y_test, y_pred, labels=labels, average=None)
precision_avg, recall_avg, f1_avg, _ = precision_recall_fscore_support(y_test, y_pred, labels=labels, average='weighted')
conf_matrix = confusion_matrix(y_test, y_pred, labels=labels)
accuracy = accuracy_score(y_test, y_pred)

print(f"\n{'='*60}")
print("MODEL EVALUATION RESULTS  (Stage 1 Binary, middle band test set)")
print(f"{'='*60}")
print(f"Accuracy:              {accuracy:.4f} ({accuracy*100:.2f}%)")
print(f"Precision (weighted):  {precision_avg:.4f}")
print(f"Recall (weighted):     {recall_avg:.4f}")
print(f"F1-Score (weighted):   {f1_avg:.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred, labels=labels, target_names=target_names))
print("\nConfusion Matrix (rows=actual, cols=predicted):")
print(conf_matrix)

# ======================================
# SAVE MODEL + METADATA DIRECTLY TO DRIVE
# ======================================
timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
model_filename    = f'rf_stage1_binary_{timestamp}.pkl'
metadata_filename = f'rf_stage1_binary_{timestamp}_metadata.json'

# Paths pointing directly to Google Drive
model_path = os.path.join(DRIVE_DIR, model_filename)
metadata_path = os.path.join(DRIVE_DIR, metadata_filename)

joblib.dump(rf_model, model_path)

metadata = {
    'timestamp': timestamp,
    'trained_datetime': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
    'pipeline_stage': 'Stage 1 — binary classification (Background vs Wetland)',
    'split_method': 'middle_row_band',
    'test_row_min': test_row_min,
    'test_row_max': test_row_max,
    'classes': labels,
    'note': (
        'Transforms original dataset classes to binary (Class 0 -> 0, Classes 1-5 -> 1). '
        'Intended to act as the first stage filter before the Stage 2 wetland-only RF model. '
        f'Test region: middle latitude band rows {test_row_min}–{test_row_max}.'
    ),
    'overall_metrics': {
        'accuracy':            float(accuracy),
        'precision_weighted':  float(precision_avg),
        'recall_weighted':     float(recall_avg),
        'f1_weighted':         float(f1_avg),
    },
    'per_class_metrics': {
        str(labels[i]): {
            'precision': float(precision[i]),
            'recall':    float(recall[i]),
            'f1_score':  float(f1[i]),
            'support':   int(support[i]),
        }
        for i in range(len(labels))
    },
    'confusion_matrix': conf_matrix.tolist(),
    'confusion_matrix_labels': labels,
    'hyperparameters': {
        'n_estimators':     200,
        'max_depth':        25,
        'min_samples_leaf': 20,
        'feature_scaling':  'none',
        'class_weight':     'balanced_binary_with_manual_boost',
        'background_boost_factor': BACKGROUND_BOOST,
        'n_jobs':           -1,
        'random_state':     42,
    },
    'dataset': {
        'source': f'{DRIVE_DIR}/wetland_dataset_middle_split.npz',
        'n_train': int(X_train.shape[0]),
        'n_test':  int(X_test.shape[0]),
        'n_features': int(X_train.shape[1]),
    },
    'class_weights': {str(k): float(v) for k, v in class_weight_dict.items()},
}

with open(metadata_path, 'w') as f:
    json.dump(metadata, f, indent=2)

print(f"\n{'='*60}")
print("MODEL SAVED TO GOOGLE DRIVE")
print(f"{'='*60}")
print(f"Model:    {model_path}")
print(f"Metadata: {metadata_path}")

# ======================================
# CELL 3: STAGE 2 MODEL TRAINING
# ======================================
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_recall_fscore_support
import numpy as np
import joblib
import os
from datetime import datetime
import json

# Load dataset
DATA_PATH = os.path.join(DRIVE_DIR, 'wetland_dataset_middle_split.npz')
print(f"Loading dataset from: {DATA_PATH}")

data = np.load(DATA_PATH)
X_train = data['X_train']
y_train = data['y_train']
X_test  = data['X_test']
y_test  = data['y_test']
test_row_min = int(data['test_row_min'])
test_row_max = int(data['test_row_max'])
data.close()

# Filter out Class 0 (Background)
train_mask = y_train != 0
test_mask  = y_test  != 0

X_train = X_train[train_mask]
y_train = y_train[train_mask]
X_test  = X_test[test_mask]
y_test  = y_test[test_mask]

print(f"\nAfter filtering Class 0:")
print(f"  Train: {X_train.shape[0]:,} samples")
print(f"  Test:  {X_test.shape[0]:,} samples")

# Recalculate class weights (Classes 1–5 only)
unique_classes, class_counts = np.unique(y_train, return_counts=True)
n_total = len(y_train)
n_classes = len(unique_classes)

class_weight_dict = {
    int(cls): float(n_total / (n_classes * count))
    for cls, count in zip(unique_classes, class_counts)
}

# Dampen Class 1 to trade recall for precision
CLASS1_DAMPEN = 0.4
class_weight_dict[1] = class_weight_dict[1] * CLASS1_DAMPEN

# Train the model
rf_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=25,
    min_samples_leaf=20,
    random_state=42,
    class_weight=class_weight_dict,
    verbose=2,
    n_jobs=-1,
)

print(f"\n{'='*60}")
print("TRAINING STAGE 2 (Wetland-only, Classes 1–5)")
print(f"{'='*60}")
rf_model.fit(X_train, y_train)

# Evaluate
y_pred = rf_model.predict(X_test)
labels = sorted(class_weight_dict.keys())
target_names = [f'Class {i}' for i in labels]

precision, recall, f1, support = precision_recall_fscore_support(y_test, y_pred, labels=labels, average=None)
precision_avg, recall_avg, f1_avg, _ = precision_recall_fscore_support(y_test, y_pred, labels=labels, average='weighted')
conf_matrix = confusion_matrix(y_test, y_pred, labels=labels)
accuracy = accuracy_score(y_test, y_pred)

print(f"\nAccuracy: {accuracy:.4f} ({accuracy*100:.2f}%)")
print("\nClassification Report:")
print(classification_report(y_test, y_pred, labels=labels, target_names=target_names))

# Save to Drive
timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
model_path = os.path.join(DRIVE_DIR, f'rf_stage2_wetland_only_{timestamp}.pkl')
metadata_path = os.path.join(DRIVE_DIR, f'rf_stage2_wetland_only_{timestamp}_metadata.json')

joblib.dump(rf_model, model_path)

metadata = {
    'timestamp': timestamp,
    'pipeline_stage': 'Stage 2 — wetland classification',
    'overall_metrics': {'accuracy': float(accuracy), 'f1_weighted': float(f1_avg)},
    'hyperparameters': {'class1_dampen_factor': CLASS1_DAMPEN}
}

with open(metadata_path, 'w') as f:
    json.dump(metadata, f, indent=2)

print(f"\nModel saved to: {model_path}")

# ======================================
# CELL 4: TWO-STAGE INFERENCE PIPELINE (AUTO-LOAD LATEST MODELS)
# ======================================
!pip install -q rasterio

import numpy as np
import joblib
import rasterio
import time
import os
import glob
drive.mount('/content/drive')
# Define directories
DRIVE_DIR = '/content/drive/My Drive/CapstoneRFData'
INPUT_TILES_DIR = os.path.join(DRIVE_DIR, 'input_tiles')
OUTPUT_PREDS_DIR = os.path.join(DRIVE_DIR, 'predictions')

os.makedirs(INPUT_TILES_DIR, exist_ok=True)
os.makedirs(OUTPUT_PREDS_DIR, exist_ok=True)

# Helper function to find the latest model by filename timestamp
def get_latest_model(prefix):
    search_pattern = os.path.join(DRIVE_DIR, f'{prefix}_*.pkl')
    files = glob.glob(search_pattern)
    if not files:
        raise FileNotFoundError(f"No models found matching pattern: {search_pattern}")

    # Sorting alphabetically naturally orders by the YYYYMMDD_HHMMSS timestamp
    latest_file = sorted(files)[-1]
    return latest_file

# Auto-discover the newest models
print("Locating latest models...")
try:
    STAGE1_MODEL_PATH = get_latest_model('rf_stage1_binary')
    STAGE2_MODEL_PATH = get_latest_model('rf_stage2_wetland_only')

    print(f"-> Found Stage 1: {os.path.basename(STAGE1_MODEL_PATH)}")
    print(f"-> Found Stage 2: {os.path.basename(STAGE2_MODEL_PATH)}\n")

    print("Loading Stage 1 (Binary) model...")
    rf_stage1 = joblib.load(STAGE1_MODEL_PATH)

    print("Loading Stage 2 (Wetland-only) model...")
    rf_stage2 = joblib.load(STAGE2_MODEL_PATH)
    print("Models ready.\n")

except FileNotFoundError as e:
    print(f"Error: {e}")
    print("Make sure you have run the training cells and the models are saved in DRIVE_DIR.")

def process_tile(input_filename):
    input_path = os.path.join(INPUT_TILES_DIR, input_filename)
    output_path = os.path.join(OUTPUT_PREDS_DIR, f"pred_{input_filename}")

    print(f"{'='*50}\nPROCESSING TILE: {input_filename}\n{'='*50}")
    start_time = time.time()

    # 1. Read embeddings
    with rasterio.open(input_path) as src:
        profile = src.profile
        img_data = src.read()

        profile.update(count=1, dtype=rasterio.uint8, nodata=255)

    n_bands, height, width = img_data.shape

    # 2. Reshape for Scikit-Learn
    img_data = np.moveaxis(img_data, 0, -1)
    X_flat = img_data.reshape(-1, n_bands)
    final_predictions = np.zeros(X_flat.shape[0], dtype=np.uint8)

    # 3. STAGE 1: Predict Background (0) vs. Wetland (1)
    stage1_preds = rf_stage1.predict(X_flat)
    wetland_mask = (stage1_preds == 1)
    num_wetland_pixels = np.sum(wetland_mask)

    print(f"  -> Found {num_wetland_pixels:,} wetland pixels "
          f"({(num_wetland_pixels/len(X_flat))*100:.1f}% of tile).")

    # 4. STAGE 2: Classify specific wetland types
    if num_wetland_pixels > 0:
        X_wetlands = X_flat[wetland_mask]
        stage2_preds = rf_stage2.predict(X_wetlands)
        final_predictions[wetland_mask] = stage2_preds

        unique, counts = np.unique(stage2_preds, return_counts=True)
        print("  -> Wetland breakdown:")
        for cls, count in zip(unique, counts):
            print(f"     Class {cls}: {count:,} pixels")

    # 5. Save output
    pred_2d = final_predictions.reshape(height, width)
    with rasterio.open(output_path, 'w', **profile) as dst:
        dst.write(pred_2d, 1)

    print(f"\nSaved to: {output_path} ({time.time() - start_time:.2f}s)")

# ======================================
# EXECUTE INFERENCE
# ======================================
# Uncomment the lines below and replace with a real tile name from your Drive
# test_tile_name = 'example_tile.tif'
# process_tile(test_tile_name)

# ======================================
# CELL 4: TWO-STAGE INFERENCE ON TEST SET
# ======================================
import numpy as np
import joblib
import os
import glob
import time
import json
from datetime import datetime
from sklearn.metrics import (classification_report, accuracy_score,
                             confusion_matrix, precision_recall_fscore_support)

DRIVE_DIR = '/content/drive/My Drive/CapstoneRFData'


# ======================================
# 1. SETUP PATHS & AUTO-DISCOVER MODELS
# ======================================
DRIVE_DIR  = '/content/drive/My Drive/CapstoneRFData'
DATA_PATH  = os.path.join(DRIVE_DIR, 'wetland_dataset_middle_split.npz')
OUTPUT_DIR = os.path.join(DRIVE_DIR, 'models') # Added to match Block 1 structure
os.makedirs(OUTPUT_DIR, exist_ok=True)

def get_latest_model(prefix):
    search_pattern = os.path.join(DRIVE_DIR, f'{prefix}_*.pkl')
    files = glob.glob(search_pattern)
    if not files:
        raise FileNotFoundError(f"No models found matching pattern: {search_pattern}")
    return sorted(files)[-1]

print("Locating and loading latest models...")
try:
    # Save the paths so we can log exactly which models were used in the metadata
    stage1_path = get_latest_model('rf_stage1_binary')
    stage2_path = get_latest_model('rf_stage2_wetland_only')

    rf_stage1 = joblib.load(stage1_path)
    rf_stage2 = joblib.load(stage2_path)
    print("Models loaded successfully.\n")
except Exception as e:
    print(f"Error: {e}")

# ======================================
# 2. LOAD THE ORIGINAL TEST DATA
# ======================================
print(f"Loading test dataset from: {DATA_PATH}")
data = np.load(DATA_PATH)
X_test = data['X_test']
y_test = data['y_test'] # Original multi-class labels (0-5)
data.close()

# ======================================
# 3. TWO-STAGE INFERENCE LOGIC
# ======================================
print(f"Running inference on {X_test.shape[0]:,} samples...")
infer_start = time.time()

# Initialize final predictions with 0 (Background)
final_predictions = np.zeros(X_test.shape[0], dtype=np.uint8)

# --- STAGE 1: Binary Filter ---
# Predict if pixel is Background (0) or Wetland (1)
stage1_preds = rf_stage1.predict(X_test)
wetland_mask = (stage1_preds == 1)
num_wetland_pixels = np.sum(wetland_mask)

print(f"  -> Stage 1 identified {num_wetland_pixels:,} pixels as potential wetland.")

# --- STAGE 2: Multi-class Wetland Classification ---
if num_wetland_pixels > 0:
    X_wetlands = X_test[wetland_mask]
    stage2_preds = rf_stage2.predict(X_wetlands)

    # Map the Stage 2 results back into the final prediction array
    final_predictions[wetland_mask] = stage2_preds
    print("  -> Stage 2 classification complete.")

infer_time = time.time() - infer_start
print(f"  -> Total inference time: {infer_time:.2f}s")

# ======================================
# 4. EVALUATION & METRICS
# ======================================
print(f"\n{'='*60}")
print("FINAL PIPELINE EVALUATION (Stage 1 + Stage 2 Combined)")
print(f"{'='*60}")

# Define labels: 0=Background, 1-5=Wetland Types
labels = [0, 1, 2, 3, 4, 5]
target_names = ['Background (0)', 'Class 1', 'Class 2', 'Class 3', 'Class 4', 'Class 5']

accuracy    = accuracy_score(y_test, final_predictions)
conf_matrix = confusion_matrix(y_test, final_predictions, labels=labels)

# Calculate precision, recall, f1 for metadata
precision, recall, f1, support = precision_recall_fscore_support(y_test, final_predictions, labels=labels, average=None)
precision_avg, recall_avg, f1_avg, _ = precision_recall_fscore_support(y_test, final_predictions, labels=labels, average='weighted')

print(f"Accuracy:              {accuracy:.4f} ({accuracy*100:.2f}%)")
print(f"Precision (weighted):  {precision_avg:.4f}")
print(f"Recall (weighted):     {recall_avg:.4f}")
print(f"F1-Score (weighted):   {f1_avg:.4f}")

print("\nFull Pipeline Classification Report:")
print(classification_report(y_test, final_predictions, labels=labels, target_names=target_names))

print("\nConfusion Matrix (Rows=Actual, Cols=Predicted):")
print(conf_matrix)

# ======================================
# 5. SAVE METADATA TO GOOGLE DRIVE
# ======================================
timestamp         = datetime.now().strftime('%Y%m%d_%H%M%S')
metadata_filename = f'two_stage_pipeline_eval_{timestamp}_metadata.json'

metadata = {
    'timestamp': timestamp,
    'evaluation_datetime': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
    'pipeline_stage': 'Two-Stage Inference Pipeline (Stage 1 Binary -> Stage 2 Wetland Multi-class)',
    'models_used': {
        'stage1_binary': os.path.basename(stage1_path),
        'stage2_wetland': os.path.basename(stage2_path)
    },
    'classes': labels,
    'overall_metrics': {
        'accuracy':           float(accuracy),
        'precision_weighted': float(precision_avg),
        'recall_weighted':    float(recall_avg),
        'f1_weighted':        float(f1_avg),
    },
    'per_class_metrics': {
        str(labels[i]): {
            'precision': float(precision[i]),
            'recall':    float(recall[i]),
            'f1_score':  float(f1[i]),
            'support':   int(support[i]),
        }
        for i in range(len(labels))
    },
    'confusion_matrix':        conf_matrix.tolist(),
    'confusion_matrix_labels': labels,
    'timing': {
        'inference_seconds': round(infer_time, 2),
    },
    'dataset': {
        'source':                      DATA_PATH,
        'n_test_samples':              int(X_test.shape[0]),
        'stage1_wetland_pixels_found': int(num_wetland_pixels)
    }
}

with open(os.path.join(OUTPUT_DIR, metadata_filename), 'w') as f:
    json.dump(metadata, f, indent=2)

print(f"\n{'='*60}")
print(f"METADATA SAVED TO DRIVE: {OUTPUT_DIR}")
print(f"{'='*60}")
print(f"Metadata: {metadata_filename}")